### ISSUE TITLE
Global minimum price disables calculation

### ISSUE THREAD

**Issue by aesthete20** [angelleye/woocommerce-price-per-word#61]
Hi there,

Just posting this to the correct forum:

I have tried on multiple occasions to set a minimum price, but when I do the plugin cannot calculate the total price.

Many thanks

**Comment by angelleye** [comment]
I'm sorry for the delayed response.  Are you still struggling with this?  Unfortunately, this plugin is not very popular yet so it's tough to make it a priority over our other more popular plugins, but we are still excited about this plugin and will certainly be making improvements to it with future updates.  

Please elaborate a little bit on what you're trying to do here and we'll see if we can reproduce the problem so that we can get it fixed.
